version: '3.8'
services:
  db:
    image: mysql:latest
    container_name: notifications-db
    env_file:
      - db.env
    ports:
      - "3306:3306"
    volumes:
      - ./startup.sql:/docker-entrypoint-initdb.d/startup.sql
      # - db_data:/var/lib/mysql
#
#volumes:
#  db_data: